version: '2'
services:
    jhipsterconf-app:
        image: jhipsterconf
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipsterconf-mysql:3306/jhipsterconf?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    jhipsterconf-mysql:
        extends:
            file: mysql.yml
            service: jhipsterconf-mysql
